services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=mjlsbkCh2z8Ft63
    command: ["redis-server", "--requirepass", "mjlsbkCh2z8Ft63"]

  email-worker:
    build:
      context: ./backend
      dockerfile: email.worker.dockerfile
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - redis
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=mjlsbkCh2z8Ft63
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["npm", "run", "emailWorker"]

  db-worker:
    build:
      context: ./backend
      dockerfile: db.worker.dockerfile
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - redis
    env_file:
      - .env
    restart: always
    environment:
      - REDIS_PASSWORD=mjlsbkCh2z8Ft63
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["npm", "run", "dbWorker"]

  cronjob:
    build:
      context: ./backend
      dockerfile: cronjob.dockerfile
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_PASSWORD=mjlsbkCh2z8Ft63
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["npm", "run", "cronJob"]

volumes:
  backend_node_modules:
  redis_data:
