services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=mjlsbkCh2z8Ft63
    command: ["redis-server", "--requirepass", "mjlsbkCh2z8Ft63"]

  email-worker:
    build:
      context: ./backend
      dockerfile: emailWorker.dockerfile
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_PASSWORD=mjlsbkCh2z8Ft63
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["node", "emailWorker.js"] # change if your entry point differs

  db-worker:
    build:
      context: ./backend
      dockerfile: dbWorker.dockerfile
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_PASSWORD=mjlsbkCh2z8Ft63
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["node", "dbWorker.js"] # change as needed

  cronjob:
    build:
      context: ./backend
      dockerfile: cronjob.dockerfile
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    restart: always
    command: ["node", "cronjob.js"] # adjust as needed

  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
    # Removed depends_on since frontend/backend are external

volumes:
  backend_node_modules:
  redis_data:
